In [35]:
!kaggle

usage: kaggle [-h] [-v] {competitions,c,datasets,d,kernels,k,models,m,files,f,config} ...
kaggle: error: the following arguments are required: command

In [36]:
!kaggle datasets download -d manishkr1754/cardekho-used-car-data

Dataset URL: https://www.kaggle.com/datasets/manishkr1754/cardekho-used-car-data
License(s): DbCL-1.0
cardekho-used-car-data.zip: Skipping, found more recently modified local copy (use --force to force download)

In [37]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [38]:
## Extract the dataset file
import zipfile
with zipfile.ZipFile('cardekho-used-car-data.zip', 'r') as zip_ref:
    zip_ref.extractall()
    print('Extracted')

Extracted

### **Used Car Price Prediction**

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import plotly as py
import plotly.express as px
import plotly.graph_objects as go

In [40]:
df = pd.read_csv('/content/cardekho_dataset.csv')
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [41]:
df.shape

(15411, 14)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

## **Data Cleaning**

**Handling Missing Values**

1.Handiling Missing Values

2.Handling Duplicates

3.Check data type

4.Understand the Dataset

In [43]:
## Check Null Values
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [44]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [45]:
##drop columns
df.drop(columns = ['Unnamed: 0','car_name','brand'],axis = 1,inplace=True)

In [46]:
### Getting All Diffrent Types of Features


## Numerical Features
num_features = [feature for feature in df.columns if df[feature].dtype !='O']
print('Number Of Numerical Features:-', len(num_features))


## Categorical Features
cat_features = [feature for feature in df.columns if df[feature].dtype =='O']
print('Number Of Categorical Features:-', len(cat_features) )


### Discrete Features
discrete_features = [feature for feature in num_features if len(df[feature].unique())<= 25]
print('Number Of Discrete Features:-', len(discrete_features))


### Continuous Features
continuous_features = [feature for feature in num_features if feature not in discrete_features]
print('Number Of Continuous Features:-',len(continuous_features))

Number Of Numerical Features:- 7
Number Of Categorical Features:- 4
Number Of Discrete Features:- 2
Number Of Continuous Features:- 5

In [47]:
print("Numerical Features :-", (num_features))
print('-'*80)
print("Categorical Features :-", (cat_features))
print('-'*80)
print("Discrete Features :-", (discrete_features))
print('-'*80)
print("Continuous Features :-", (continuous_features))

Numerical Features :- ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']
--------------------------------------------------------------------------------
Categorical Features :- ['model', 'seller_type', 'fuel_type', 'transmission_type']
--------------------------------------------------------------------------------
Discrete Features :- ['vehicle_age', 'seats']
--------------------------------------------------------------------------------
Continuous Features :- ['km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [48]:
### Independent and Dependent Features
from sklearn.model_selection import train_test_split

X = df.drop(columns = ['selling_price'],axis = 1)
y = df['selling_price']

In [49]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

### **Feature Encoding and scaling**

**One Hot Encoding for columns which had lesser unique values and not ordinal**



* One hot Encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to Ml algorithms to do better job in prediction

In [50]:
len(df['model'].unique())

120

In [51]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [52]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(df['model'])

In [53]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [54]:
print(len(df['seller_type'].unique()))

print(len(df['fuel_type'].unique()))

print(len(df['transmission_type'].unique()))

3
5
2

In [55]:
## Create Column Transfoemer with 3 types of transformers

num_features = X.select_dtypes(exclude = "object").columns

onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer


numeric_transfomer = StandardScaler()
oh_transformer = OneHotEncoder(drop = 'first')

preprocessor = ColumnTransformer(
    [

     ("OneHotEncoder",oh_transformer,onehot_columns),
     ("StandardScaler",numeric_transfomer,num_features)




     ],remainder = 'passthrough'  ##
)

In [56]:
pd.DataFrame(X)

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
15406,117,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
15407,42,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
15408,77,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
15409,114,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
15410,25,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [57]:
X = preprocessor.fit_transform(X)

In [58]:
## Separate dataset into train and test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

((12328, 14), (3083, 14), (12328,), (3083,))

In [59]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]])

### **Model TRaining and Model Selection**

In [60]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error,accuracy_score

In [61]:
## Create the Function to Evalute the model
def evaluate_moldel(true,predicted):
    mse = mean_squared_error(true,predicted)
    mae = mean_absolute_error(true,predicted)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(true,predicted)
    r2_square = r2_score(true,predicted)
    return mse,rmse,mae,r2_square

In [62]:
## Begining Modle TRaining

models = {
    "Linear Regression":LinearRegression(),
    "Ridge":Ridge(),
    "Lasso":Lasso(),
    "KNN":KNeighborsRegressor(),
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestRegressor()
}

for i in range(len(list(models))):
  model = list(models.values())[i]
  model.fit(X_train,y_train)

  ##Make Predictions
  y_pred = model.predict(X_test)
  y_test_pred = model.predict(X_train)

  ##Evalute the train and test dataset
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  ##Evaluate the model
  model_train_mse,model_train_rmse,model_train_mae,model_train_r2_square = evaluate_moldel(y_test,y_pred)


  model_test_mse,model_test_rmse,model_test_mae,model_test_r2_square = evaluate_moldel(y_test,y_pred)



  print(list(models.keys())[i])


  print(list(models.keys())[i])


## Model Performance for training
  print("Model Performace for Trining set")

  print("-Root Mean Squared Error : {:.4f}".format(model_train_rmse))
  print("-Mean Absolute Error : {:.4f}".format(model_train_mae))
  print("-Mean Squared Error : {:.4f}".format(model_train_mse))
  print("-R2 Square : {:.4f}".format(model_train_r2_square))

  print('-'*80)

 ## modle Performanece for Test
  print("Model Performance for the test Set")
  print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
  print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
  print("- Mean Squared Error: {:.4f}".format(model_test_mse))
  print("- R2 Square: {:.4f}".format(model_test_r2_square))


  print("="*70)
  print('\n')

Linear Regression
Linear Regression
Model Performace for Trining set
-Root Mean Squared Error : 502543.5930
-Mean Absolute Error : 279618.5794
-Mean Squared Error : 252550062888.5656
-R2 Square : 0.6645
--------------------------------------------------------------------------------
Model Performance for the test Set
- Root Mean Squared Error: 502543.5930
- Mean Absolute Error: 279618.5794
- Mean Squared Error: 252550062888.5656
- R2 Square: 0.6645
======================================================================


Ridge
Ridge
Model Performace for Trining set
-Root Mean Squared Error : 502533.8230
-Mean Absolute Error : 279557.2169
-Mean Squared Error : 252540243247.9686
-R2 Square : 0.6645
--------------------------------------------------------------------------------
Model Performance for the test Set
- Root Mean Squared Error: 502533.8230
- Mean Absolute Error: 279557.2169
- Mean Squared Error: 252540243247.9686
- R2 Square: 0.6645
======================================================================


Lasso
Lasso
Model Performace for Trining set
-Root Mean Squared Error : 502542.6696
-Mean Absolute Error : 279614.7461
-Mean Squared Error : 252549134806.7814
-R2 Square : 0.6645
--------------------------------------------------------------------------------
Model Performance for the test Set
- Root Mean Squared Error: 502542.6696
- Mean Absolute Error: 279614.7461
- Mean Squared Error: 252549134806.7814
- R2 Square: 0.6645
======================================================================


KNN
KNN
Model Performace for Trining set
-Root Mean Squared Error : 253071.9428
-Mean Absolute Error : 112672.8917
-Mean Squared Error : 64045408211.3607
-R2 Square : 0.9149
--------------------------------------------------------------------------------
Model Performance for the test Set
- Root Mean Squared Error: 253071.9428
- Mean Absolute Error: 112672.8917
- Mean Squared Error: 64045408211.3607
- R2 Square: 0.9149
======================================================================


Decision Tree
Decision Tree
Model Performace for Trining set
-Root Mean Squared Error : 579130.5479
-Mean Absolute Error : 142919.9238
-Mean Squared Error : 335392191539.2880
-R2 Square : 0.5545
--------------------------------------------------------------------------------
Model Performance for the test Set
- Root Mean Squared Error: 579130.5479
- Mean Absolute Error: 142919.9238
- Mean Squared Error: 335392191539.2880
- R2 Square: 0.5545
======================================================================


Random Forest
Random Forest
Model Performace for Trining set
-Root Mean Squared Error : 229277.0175
-Mean Absolute Error : 102439.9532
-Mean Squared Error : 52567950763.9055
-R2 Square : 0.9302
--------------------------------------------------------------------------------
Model Performance for the test Set
- Root Mean Squared Error: 229277.0175
- Mean Absolute Error: 102439.9532
- Mean Squared Error: 52567950763.9055
- R2 Square: 0.9302
======================================================================

In [86]:
### Intialize the Few Parameters Tuning
## Selct KNN and Random Forest Regressor and do hyper parameters

from sklearn.model_selection import GridSearchCV
knn_params = {"n_neighbors":[2,3,10,20,40,50]}

rf_params = {

             "max_depth":[5,8,15,None,10],
             "max_features":[5,7,"auto",10],
             "min_samples_split":[2,8,15,20],
             "n_estimators":[100,200,500,1000]

             }

In [87]:
## Model List For HyperParameter Tuning


randomcv_models =[


    ("KNN",KNeighborsRegressor(),knn_params),
    ("Random Forest",RandomForestRegressor(),rf_params)
]

In [88]:
#hyperparamaeter Tuning


from sklearn.model_selection import RandomizedSearchCV


model_param = {}

for name,model,params in randomcv_models:
  random = RandomizedSearchCV(
      estimator = model,
      param_distributions=params,
      n_iter = 100,
      cv =3,
      verbose = 2,
      n_jobs = -1
  )



  random.fit(X_train,y_train)
  model_param[name] = random.best_params_


for model_name in model_param:
  print(f"------------------------------------------------{model_name}-------------------------------")
  print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
------------------------------------------------KNN-------------------------------
{'n_neighbors': 10}
------------------------------------------------Random Forest-------------------------------
{'n_estimators': 500, 'min_samples_split': 2, 'max_features': 5, 'max_depth': None}

In [ ]:
### REtraining the Model's with the best Parameters

models = {


}